#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2017 - 2026 Badge.Team contributors
# SPDX-License-Identifier: MIT

sed -n 'w /tmp/chip.v'

iverilog -t null `yosys-config --datdir/ice40/cells_sim.v` /tmp/chip.v
error=$?

rm /tmp/chip.v

exit $error
