name: Laravel PHPStan, Swagger and Pest

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        php-versions: ['8.0', '8.1']
    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: badge
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v1
    - name: Install Linux packages
      run: sudo apt update && sudo apt install -y --no-install-recommends pyflakes git iverilog arachne-pnr arachne-pnr-chipdb fpga-icestorm fpga-icestorm-chipdb
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: xdebug, imagick
        ini-values: "post_max_size=256M"
    - name: Check PHP Version
      run: php -v
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist && yarn install --production
    - name: Generate key
      run: php artisan key:generate
    - name: LaraStan
      run: vendor/bin/phpstan analyse
    - name: Security Check
      run: php artisan security-check:now
    - name: Swagger generate
      run: php artisan l5-swagger:generate
    - name: Populate DB
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 33306
        DB_DATABASE: badge
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --force
    - name: Generate sitemap
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 33306
        DB_DATABASE: badge
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan sitemap:generate
    - name: Config clear
      run: php artisan config:clear
    - name: Route clear
      run: php artisan route:clear
    - name: Execute (Unit and Feature) tests via Pest
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 33306
        DB_DATABASE: badge
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_TEST_DATABASE: badge
        DB_TEST_USERNAME: root
        DB_TEST_PASSWORD: root
      run: vendor/bin/pest
