# SPDX-FileCopyrightText: 2017 - 2026 Badge.Team contributors
# SPDX-License-Identifier: MIT

name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  php-codesniffer:
    name: PHP CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: gd, gmp, zip, intl, exif, pcntl, mbstring, fileinfo
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: PHP CodeSniffer
        run: vendor/bin/phpcs -q --warning-severity=0

  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install npm dependencies
        run: npm ci
      - name: markdownlint
        run: npx markdownlint '**/*.md' --ignore node_modules --ignore vendor

  reuse:
    name: REUSE compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check licensing
        uses: fsfe/reuse-action@v5
