name: Create release package

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install npm dependencies
        run: yarn
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
      - name: Composer install (for indexing of vendor blade classes)
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.REPO_READ_ONLY_TOKEN }}"}}'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev
      - name: Run build task
        run: yarn build
      - name: Clean build
        run: rm -r node_modules .git
      - name: Clear config cache
        run: php artisan config:clear
      - name: Clear route cache
        run: php artisan route:clear
      - run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > public/version.json'
        shell: bash
      - name: Make ./storage group writable for, code_owner != run_user
        run: chmod 775 ./storage
      - name: Create tar
        run: tar -czf Hatchery_${{ env.RELEASE_VERSION }}.tar.gz ./app ./bootstrap ./config ./database ./public ./resources ./routes ./storage ./vendor ./composer.json ./artisan ./linters
      - name: Upload release tar
        uses: actions/upload-artifact@v2
        with:
          name: Hatchery_${{ env.RELEASE_VERSION }}
          path: Hatchery_${{ env.RELEASE_VERSION }}.tar.gz
